Added set of items and masster password
ondrys123/wuss pull request #17
Opened 2021-04-21 12:53 UTC by ondrys123

closes #8

2021-04-22 23:25 UTC, mdugacek requested changes

2021-04-22 23:25 UTC, mdugacek commented on trusted/item.hpp
> +inline bool operator<(const item_t& l_, const item_t& r)
Naming of arguments is not consistent.

2021-04-23 09:21 UTC, ondrys123 commented on trusted/item.hpp
> +inline bool operator<(const item_t& l_, const item_t& r)
fixed

2021-04-23 12:12 UTC, mdugacek approved these changes
lgtm

2021-04-23 13:40 UTC, tajriis approved these changes

2021-04-23 22:50 UTC, merged