Store
ondrys123/wuss pull request #22
Opened 2021-04-28 17:37 UTC by tajriis

Closes #14

2021-04-28 18:30 UTC, mdugacek requested changes

2021-04-28 18:30 UTC, mdugacek commented on trusted/wallet.cpp
> +    sgx_status_t status = wallet_exists(&ret);
Is it ok that the return value is not used?
If yes, do we have to store it?

2021-04-28 18:30 UTC, mdugacek commented on trusted/wallet.cpp
> +        on_error("[update_stored_wallet] Wallet not sealed");
I think that `[update_stored_wallet] Failed to seale wallet`  would be better error message.

2021-04-28 18:30 UTC, mdugacek commented on trusted/wallet.cpp
> +        on_error("[update_stored_wallet] Wallet not stored to file");
I think that `[update_stored_wallet] Failed to store wallet` would be better error message.

2021-04-28 18:30 UTC, mdugacek commented on trusted/wallet.cpp
> +        on_error("[load_stored_wallet] Wallet not loaded from file");
I think that `[load_stored_wallet] Failed to load wallet from file` is better error message.

2021-04-28 18:30 UTC, mdugacek commented on trusted/wallet.cpp
> +        on_error("[load_stored_wallet] Wallet not unsealed");
I think that `[load_stored_wallet] Failed to open wallet` is better error message.

2021-04-28 18:30 UTC, mdugacek commented on trusted/wallet.hpp
> +    //void update_stored_wallet() const;
Delete comment.

2021-04-28 18:30 UTC, mdugacek commented on trusted/wallet.hpp
> +    //void load_stored_wallet() const;
Delete comment.

2021-04-28 18:30 UTC, mdugacek commented on trusted/wallet.cpp
> +    bool stored_status = load_wallet(&ret, sealed_data.get(), sealed_size);
Could be `const auto` and renamed to `load_success`.

2021-04-28 18:30 UTC, mdugacek commented on trusted/wallet.cpp
> +    size_t wallet_size = sealed_size - sizeof(sgx_sealed_data_t);
Add `const`.

2021-04-28 18:30 UTC, mdugacek commented on trusted/wallet.cpp
> +    sgx_status_t status = get_file_size(&sealed_size);
Type could be `const auto`.

2021-04-28 18:30 UTC, mdugacek commented on trusted/wallet.cpp
> +    size_t wallet_size = get_wallet_total_size() + _master_password.size() + 1;
Could be `const auto` instead of `size_t`

2021-04-28 18:30 UTC, mdugacek commented on trusted/wallet.cpp
> +    size_t sealed_size = wallet_size + sizeof(sgx_sealed_data_t);
Could be `const auto` instead of `size_t`

2021-04-28 18:30 UTC, mdugacek commented on trusted/wallet.hpp
>  private:
This `private` section is empty so I think that you can delete it.

2021-04-28 18:30 UTC, mdugacek commented on trusted/wallet.cpp
> +    for (const item_t& item : _items)
Type could be `const auto`.

2021-04-28 20:02 UTC, ondrys123 requested changes
Some files are not formatted, try to format them using `clang-format`

2021-04-28 20:02 UTC, JoyOfMadness commented on misc/enclave.edl
> +        int wallet_exists(void);
I don't think this is needed, we have `get_file_size` which returns 0 if file doesn't exist

2021-04-28 20:02 UTC, JoyOfMadness commented on trusted/storage_handler.cpp
> +#include "sgx_trts.h"
I don't think this header is needed

2021-04-28 20:02 UTC, JoyOfMadness commented on trusted/storage_handler.cpp
> +sgx_status_t seal_wallet(const uint8_t* wallet_, size_t wallet_size, sgx_sealed_data_t* sealed_data, size_t sealed_size )
For the sake of consistency, all function arguments should end with `_`, i.e. `wallet_size_`, `sealed_data_` ...

2021-04-28 20:02 UTC, JoyOfMadness commented on trusted/storage_handler.hpp
> +#include "sgx_trts.h"
Again, probably not needed

2021-04-28 20:02 UTC, JoyOfMadness commented on trusted/wallet.cpp
> +    auto* output_ = data.get();
Ordinary variable shouldn't have trailing `_`

2021-04-28 20:02 UTC, JoyOfMadness commented on trusted/wallet.cpp
> +        on_error("[update_stored_wallet] Failed to seale wallet");
If sealing failed, we should exit function here using `return;`

2021-04-28 20:02 UTC, JoyOfMadness commented on trusted/wallet.cpp
> +    size_t sealed_size;
```suggestion
    size_t sealed_size{};
```

2021-04-28 20:02 UTC, JoyOfMadness commented on trusted/wallet.cpp
> +    _items = items;
```suggestion
    _items = std::move(items);
```

2021-04-28 20:02 UTC, JoyOfMadness commented on untrusted/enclave_wrapper.cpp
> +    file.close();
This line is unnecessary, file gets closed on destruction

2021-04-29 11:44 UTC, mdugacek approved these changes

2021-04-29 11:44 UTC, mdugacek commented on trusted/wallet.cpp
> +        on_error("[update_stored_wallet] Failed to seale wallet");
Sorry for typo, should be `seal` and not `sealE`.

2021-04-29 12:25 UTC, ondrys123 approved these changes
Looks good to me

2021-04-29 12:29 UTC, merged